name: Test ascii art

on: [push]

jobs:
  ascii:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          python3 -m pip install ascii-magic
      - name: Run
        run: python3 tools/ascii_art.py
